[package]
name = "kateth"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.4.2", features = ["std", "serde"] }
blst = "0.3.11"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
sha2 = "0.10.8"

[dev-dependencies]
rand = "0.8.5"
