name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: LFS
      run: git lfs pull
    - name: build
      run: cargo build --all --all-targets --all-features --verbose
    - name: test
      run: cargo test --all --all-features --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: format
      run: cargo fmt --all --check
    - name: clippy
      run: cargo clippy --all --all-targets --all-features --verbose
